import { createEngine as createAIEngine } from '@ps154/ai';
import type { Canonical, Classification, Config, FormatId, Span } from '@ps154/shared';
import { redis } from './db';

const ai = createAIEngine({ redis });

export interface RunFormatParams {
  formatId: FormatId;
  source: {
    id: string;
    classification: Classification;
    spans: Span[];
    raw_content: string;
    source_hash: string;
  };
  canonical: Canonical;
  config: Config;
  onPhase?: (status: 'running' | 'validating' | 'revising', detail?: string) => unknown;
}

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

/** Shown on every card and written to the audit log, so stub output is never mistaken for model output. */
const STUB_MODEL = 'offline-stub (no model ran)';
let stubWarned = false;

function warnStub(stage: string) {
  if (!stubWarned) {
    stubWarned = true;
    console.warn(
      '\n*** OFFLINE STUB ACTIVE ***\n' +
        'GROQ_API_KEY is unset or a placeholder, so no model is being called.\n' +
        'Output is copied from the source, is NOT verified, and is marked unverified\n' +
        'on every card. Set GROQ_API_KEY before any demo or measurement.\n'
    );
  }
  console.warn(`[Engine] ${stage}: offline stub`);
}

/** The stub verified nothing, and says so rather than reporting a clean pass. */
const STUB_VERIFICATION = {
  passed: false,
  revised: false,
  fixes: [],
  open_issues: [
    {
      check: 'stub' as const,
      key: 'stub:no-model',
      detail:
        'Generated by the offline stub because no model was reachable. Nothing was verified: ' +
        'the text is copied from the source and no identifier, hedge or limit check ran.',
    },
  ],
};

export const engine = {
  async extractCanonical(source: {
    id: string;
    classification: Classification;
    spans: Span[];
    raw_content: string;
    source_hash: string;
  }) {
    try {
      if (process.env.GROQ_API_KEY && process.env.GROQ_API_KEY !== 'gsk_placeholder') {
        return await ai.extractCanonical(source);
      }
    } catch (e: any) {
      // A blocked egress is a policy failure, never something to paper over with a stub.
      if (e?.constructor?.name === 'EgressBlocked') throw e;
      console.warn('[Engine] Model extraction unavailable, using the offline stub:', e.message);
    }

    warnStub('extraction');
    const firstSpan = source.spans[0]?.span_id ?? 'span_1';
    // Every field here is copied from the source, never invented. The stub exists so the
    // pipeline can be exercised without a model; it must not put entities, indicators or
    // recommendations into the index that the source does not contain.
    const canonical: Canonical = {
      title: source.raw_content.slice(0, 80).replace(/\n.*/s, '') || 'Untitled source',
      severity: { value: 'unknown', source_refs: [] },
      entities: [],
      events: [
        {
          summary: source.spans[0]?.text ?? 'No content extracted.',
          when: null,
          source_refs: [firstSpan],
        },
      ],
      affected_systems: [],
      indicators: [],
      key_facts: source.spans.slice(0, 5).map((s) => ({
        text: s.text,
        status: 'fact' as const,
        source_refs: [s.span_id],
      })),
      recommendations: [],
    };

    return {
      canonical,
      meta: { provider: 'local' as const, model: STUB_MODEL, latency_ms: 50 },
    };
  },

  async runFormat(params: RunFormatParams) {
    await params.onPhase?.('running');
    try {
      if (process.env.GROQ_API_KEY && process.env.GROQ_API_KEY !== 'gsk_placeholder') {
        const res = await ai.runFormat({
          format: params.formatId,
          source: params.source,
          canonical: params.canonical,
          config: params.config,
          classification: params.source.classification,
          spans: params.source.spans,
        } as any);

        await params.onPhase?.('validating');

        const grounding_score =
          typeof (res as any).grounding_score === 'number'
            ? (res as any).grounding_score
            : res.grounding && res.grounding.total_claims > 0
            ? res.grounding.grounded_count / res.grounding.total_claims
            : 1.0;

        return {
          content: (res as any).artifact ?? (res as any).content,
          claims: res.claims,
          grounding_score,
          verification: res.verification,
          meta: {
            provider: res.meta.provider,
            model: res.meta.model,
            fallback_reason: res.meta.fallback_reason ?? null,
            attempts: (res.meta as any).attempts ?? 1,
            latency_ms: res.meta.latency_ms,
            perturbed: (res.meta as any).perturbed ?? false,
          },
        };
      }
    } catch (e: any) {
      // A blocked egress is a policy failure, never something to paper over with a stub.
      if (e?.constructor?.name === 'EgressBlocked') throw e;
      console.warn(`[Engine] Format ${params.formatId} generation fell back to the stub:`, e.message);
    }

    warnStub(`generation (${params.formatId})`);
    await sleep(200);
    await params.onPhase?.('validating');
    await sleep(100);

    const spans = params.source.spans;
    const s1 = spans[0]?.span_id ?? 'span_1';
    const s2 = spans[1]?.span_id ?? s1;
    const s3 = spans[2]?.span_id ?? s1;

    const claim1 = {
      id: 'c1',
      text: spans[0]?.text ?? 'Critical perimeter activity recorded.',
      source_refs: [s1],
      status: 'fact' as const,
      grounded: true,
    };
    const claim2 = {
      id: 'c2',
      text: spans[1]?.text ?? 'Containment protocols successfully initiated across endpoints.',
      source_refs: [s2],
      status: 'fact' as const,
      grounded: true,
    };
    const claim3 = {
      id: 'c3',
      text: spans[2]?.text ?? 'No persistent unauthorized lateral movement detected.',
      source_refs: [s3],
      status: 'fact' as const,
      grounded: false,
    };

    let content: unknown;
    // grounded:false on every claim — no grounding check ran, so nothing may claim to be grounded.
    const claims = [claim1, claim2, claim3].map((c) => ({ ...c, grounded: false }));
    const [stub1, stub2, stub3] = claims;

    switch (params.formatId) {
      case 'advisory':
        content = {
          title: params.canonical.title || 'National Security Advisory',
          severity: params.canonical.severity ?? { value: 'high', source_refs: [s1] },
          summary: [stub1, stub2],
          affected_systems: [stub2],
          indicators: [],
          mitigations: [stub3],
          references: [],
        };
        break;

      case 'executive_summary':
        content = {
          headline: params.canonical.title || 'Executive Security Briefing',
          key_points: [stub1, stub2, stub3],
          impact: [stub2],
          decisions_required: [stub3],
        };
        break;

      case 'linkedin_post':
        content = {
          hook: stub1,
          body: [stub2, stub3],
          hashtags: [],
        };
        break;

      case 'x_thread':
        content = {
          tweets: [
            { index: 1, sentences: [stub1] },
            { index: 2, sentences: [stub2] },
            { index: 3, sentences: [stub3] },
          ],
        };
        break;

      case 'video_package':
      default:
        content = {
          title: params.canonical.title || 'Incident Brief Video Package',
          total_duration: 60,
          scenes: [
            { n: 1, duration: 20, visual: 'Situation overview and radar telemetry', on_screen_text: stub1, narration: stub1 },
            { n: 2, duration: 20, visual: 'Containment actions and affected systems', on_screen_text: stub2, narration: stub2 },
            { n: 3, duration: 20, visual: 'Summary and recommended next steps', on_screen_text: stub3, narration: stub3 },
          ],
        };
        break;
    }

    return {
      content,
      claims,
      grounding_score: 0,
      verification: STUB_VERIFICATION,
      meta: {
        provider: 'local' as const,
        model: STUB_MODEL,
        fallback_reason: null,
        attempts: 1,
        latency_ms: 300,
        perturbed: false,
      },
    };
  },
};
